// <auto-generated />
using System;
using Data.Lib;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Data.Lib.Migrations
{
    [DbContext(typeof(DataDbContext))]
    [Migration("20190217151014_intial")]
    partial class intial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Data.Lib.Member", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ContactNo");

                    b.Property<DateTime>("DateOfBirth");

                    b.Property<string>("Email");

                    b.Property<string>("FatherName");

                    b.Property<string>("FullName");

                    b.Property<string>("Gender");

                    b.Property<string>("MemberNo");

                    b.Property<string>("NationalNo");

                    b.Property<string>("PermanentAddress");

                    b.Property<string>("PresentAddress");

                    b.HasKey("Id");

                    b.HasIndex("MemberNo")
                        .IsUnique()
                        .HasFilter("[MemberNo] IS NOT NULL");

                    b.HasIndex("NationalNo")
                        .IsUnique()
                        .HasFilter("[NationalNo] IS NOT NULL");

                    b.ToTable("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
